project:
  type: website
  output-dir: docs

website:
  title: "wearingwiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - BaseSizeGuide.qmd
      - CarriesByWrapSize.qmd
      - WovenWrapSizes.qmd
      - WrapPasses.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



