---
title: "Base Minus 3 Carries"
format:
  html:
    code-fold: true
jupyter: python3
---

## Front Carries
- [Front Reinforced Torso Sling (FRTS)](FrontReinforcedTorsoSling.html)
- [Half Front Wrap Cross Carry (Half FWCC)](HalfFrontWrapCrossCarry.html)
- [Semi Front Wrap Cross Carry (Semi FWCC)](SemiFrontWrapCrossCarry.html)

## Hip Carries
- [Hip Cross Carry (HCC)](HipCrossCarry.html)
- [Hip Kangaroo Carry (HKC)](HipKangarooCarry.html)
- [Hip Reinforced Torso Sling (HRTS)](HipReinforcedTorsoSling.html)
- [Poppins Hip Carry](Poppins.html)

## Back Carries
- [Back Reinforced Torso Sling (BRTS) _aka Half Double Hammock_](BackReinforcedTorsoSling.html)
- [Double Hammock Double Rings (DHDR)](DoubleHammockDoubleRings.html)
- [Double Sling (DS)](DoubleSling.html)
- [Half Jordan's Back Carry (HJBC)](HalfJordansBackCarry.html)
- [Knotless Ruck](KnotlessRuck.html)
- [Lola's Back Carry](LolasBackCarry.html)
- [Reinforced Rear Ruck (RRR) _aka Pirate Carry_](ReinforcedRearRuck.html)
- [Shepherd's Back Carry](ShepherdsBackCarry.html)
- [Short Back Cross Carry (SBCC)](ShortBackCrossCarry.html)

