---
title: "Base Size Carries"
format:
  html:
    code-fold: true
jupyter: python3
---

**Base Size** is defined as the woven wrap size needed to do [Front Wrap Cross Carry](FrontWrapCrossCarry.html). Base Size can be affected by the size of the wearee, wrap thickness, and taper depth. The [Base Size Guide](BaseSizeGuide) provides some guidance for finding one's Base Size, but the only way to know for sure is to start wrapping!

## Front Carries
- [Front Cross Carry](FrontCrossCarry.html)  
- [Front Double Hammock](FrontDoubleHammock.html)  
- [Front Torso Cross Carry](FrontTorsoCrossCarry.html)  
- [Front Wrap Cross Carry](FrontWrapCrossCarry.html)  
- [Pocket Wrap Cross Carry](PocketWrapCrossCarry.html)  
- [Reinforced Kangaroo](ReinforcedKangaroo.html)

## Hip Carries
- [Hip Wrap Cross Carry](HipWrapCrossCarry)  
- [Reinforced Robin's Hip Carry](ReinforcedRobinsHipCarry)

## Back Carries
- [Back Wrap Cross Carry](BackWrapCrossCarry)  
- [Charlie's Cross Carry](CharliesCrossCarry)  
- [Double Hammock](DoubleHammock)  
- [Double Hammock Wiggleproof](DoubleHammockWiggleproof)  
- [Double Sling Shoulder to Shoulder](DoubleSlingShoulderToShoulder)  
- [Mermaid Carry](MermaidCarry)  
- [Ring Jordan's Back Carry](RingJordansBackCarry)  
- [Torso Wrap Cross Carry](TorsoWrapCrossCarry)
