---
title: "Double Sling Shoulder to Shoulder"
format:
  html:
    code-fold: true
jupyter: python3
---

| | 
|---|---
|abbreviation	|DSS2S
|type	|back carry
|pass types used	|Traditional Sling Pass, Reinforcing Pass
|size	|Base Size
|finish variations|	
|number of shoulders	|2
|level	|advanced
|type of wrap	|Woven Wrap
|characteristics	|Shoulder Flip
|good for	|Leaners, Toddlers and Support

## Carry Recipe
_Double Sling Shoulder to Shoulder – Base Size – 2 Traditional Sling Passes + 2 Bunched Reinforcing Passes_
- Off center Traditional Sling Pass over baby on back with long tail over shoulder
- Short tail comes across in bunched chest pass over long tail
- Shoulder flip long tail
- Traditional Sling Pass with tail coming up through chest belt
- Bring tails around for Bunched Reinforcing Passes
- TIF & spread shoulders

## Tutorial Links
### Links to photo tutorials
### Links to silent tutorials
### Links to captioned tutorials
### Links to tutorials (accessibility not yet evaluated)
