---
title: "Half Jordan's Back Carry"
format:
  html:
    code-fold: true
jupyter: python3
---

| | 
|---|---
|abbreviation	|HJBC
|type	|back carry
|pass types used	|Traditional Sling Pass, Cross Pass
|size	|Base Minus 3
|finish variations|	
|number of shoulders	|2
|level	|advanced
|type of wrap	|Woven Wrap
|characteristics	|optional Shoulder Flip
|good for	|Straighteners, Leaners, Toddlers and Support

## Carry Recipe
_Half Jordan’s Back Carry – Base Size Minus 3 – Traditional Sling Pass + Cross Pass or Wiggleproof Pass_

### Standard Version
- Off center Traditional Sling Pass over baby on back with short tail to hip over shoulder
- Shoulder flip with long tail
- Across baby and under leg for cross pass
- TAS/CCCB/Knotless

### No Shoulder Flip Version
- Off center Traditional Sling Pass over baby on back with long tail over shoulder
- Long tail under arm and baby’s leg for a Wiggleproof Pass
- TAS/ CCCB/ Knotless

### Symmetrical Half Jordan’s Back Carry
- Off center “Hammock” Cross Pass over baby on back with long tail over shoulder
- Long tail under arm and over baby for Traditional Sling Pass
- TAS/ CCCB/ Knotless

## Tutorial Links
### Links to photo tutorials
### Links to silent tutorials
### Links to captioned tutorials
### Links to tutorials (accessibility not yet evaluated)
