---
title: "Maxine's Back Carry"
format:
  html:
    code-fold: true
jupyter: python3
---

| | 
|---|---
|abbreviation	|
|type	|back carry
|pass types used	|Ruck Pass, Reinforcing Pass, Torso Pass
|size	|Base Minus 1
|finish variations|	
|number of shoulders	|2
|level	|advanced
|type of wrap	|Woven Wrap
|characteristics	|
|good for	|Leaners, Toddlers and Support

## Carry Recipe
_Maxine's Back Carry - Base Size Minus 1 - Ruck Pass + Reinforcing Pass + Torso Pass_

- Start wrap off center, with short tail hanging to midway between wearer's hip and shoulders
- Ruck pass over baby; pin short tail under chin
- Bring long tail down to wearer's waist to pass over baby's legs
- Bunched reinforcing pass
- Bring bunch long tail around wearer's waist for waist belt
- Spread long tail over baby for Torso Pass
- Tighten and bring long tail up to short tail to finish
- Candy cane chest belt

## Tutorial Links
### Links to photo tutorials
### Links to silent tutorials
### Links to captioned tutorials
### Links to tutorials (accessibility not yet evaluated)
