---
title: "Robin's Hip Carry"
format:
  html:
    code-fold: true
jupyter: python3
---

| | 
|---|---
|abbreviation	|RHC
|type	|hip carry
|pass types used	|Traditional Sling Pass
|size	|Base Minus 2
|finish variations|RHC with Ring
|number of shoulders	|1
|level	|beginner
|type of wrap	|Woven Wrap
|characteristics	|Poppable
|good for	|Leaners, Nursing, Sleep Transfer, Toddlers and Support

## Carry Recipe
### Standard Robin's Hip Carry
_Robin’s Hip Carry – Base Size Minus 2 – 2 Traditional Sling Passes_

- Middle marker on spine for diagonal pass against back
- Under arm tail crosses chest and over other tail
- Flip the over arm tail over shoulder to the back
- Put baby in pouch
- Both tails come over baby’s legs and TUB

### Robin's Hip Carry with Ring
_Robin’s Hip Carry with Ring – Base Size Minus 2 – 2 Traditional Sling Passes_

- Fold wrap in half lengthwise and thread one ring onto both tails
- Place ring in corsage position and wrap over you to form a Traditional Sling Pass
- Tighten both tails
- Slide baby into pocket and spread both rebozo passes
- TUB

## Tutorial Links
### Links to photo tutorials
### Links to silent tutorials
### Links to captioned tutorials
### Links to tutorials (accessibility not yet evaluated)
