---
title: "Shepherd's Back Carry"
format:
  html:
    code-fold: true
jupyter: python3
---

| | 
|---|---
|abbreviation	|
|type	|back carry
|pass types used	|Traditional Sling Pass
|size	|Base Minus 3
|finish variations|variation with cross/wiggleproof passes is good for Straighteners	
|number of shoulders	|2
|level	|
|type of wrap	|Woven Wrap
|characteristics	|
|good for	|Leaners, Toddlers and Support

## Carry Recipe
### _Shepherd's Back Carry – Base Size Minus 3 – 2 Traditional Sling Passes_

- Off center Traditional Sling Pass over baby on back with short tail to hip coming over shoulder
- Bunched or spread Chest Pass with long tail over short tail
- Tail under arm for Traditional Sling Pass
- Tail over shoulder and TIF

### _Shepherd's Back Carry For Leg Straighteners – Base Size Minus 3 – Cross Pass + Wiggleproof Pass_
- Off center Cross Pass over baby on back with short tail to hip coming over shoulder
- Bunched or spread Chest Pass with long tail over short tail
- Wiggleproof Pass with tail over shoulder and Tie in Front

## Tutorial Links
### Links to photo tutorials
### Links to silent tutorials
### Links to captioned tutorials
### Links to tutorials (accessibility not yet evaluated)
