---
title: "Short Cross Carry"
format:
  html:
    code-fold: true
jupyter: python3
---

| | 
|---|---
|abbreviation	|SCC
|type	|front carry
|pass types used	|Cross Pass
|size	|Base Minus 2
|finish variations|With Ring
|number of shoulders	|2
|level	|
|type of wrap	|Woven Wrap
|characteristics	|Poppable, optionally Uses Rings
|good for	|Straighteners, Nursing, Sleep Transfer, Toddlers and Support

## Carry Recipe
### Basic SCC
_Short Cross Carry – Base Size Minus 2 – 2 Cross Passes_

- Drape the bunched wrap off center on your back with both tails coming over your shoulders
- Long tail crosses over short tail in front
- Bring long tail to the back and go through the loop and Tie at Side
- Place baby in the inner cross and then outer cross and spread

### Ring Variation
_Short Cross Carry – Base Size Minus 2 – 2 Cross Passes_

- Thread a ring to the middle of your wrap
- Place at the center of your back with tails over your shoulders
- Cross in front and thread each tail through the ring towards your back
- Place baby in the inner cross and then outer cross and spread

## Tutorial Links
### Links to photo tutorials
### Links to silent tutorials
### Links to captioned tutorials
### Links to tutorials (accessibility not yet evaluated)
